<?php
// module/Album/view/album/album/edit.phtml:

$title = 'Edit album';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'product',
    array(
        'action' => 'edit',
        'id'     => $this->id,
    )
));
$form->prepare();
echo $this->form()->openTag($form);
echo $this->formHidden($form->get('productid'));
?>
<div class="form-group">
    <?php
    echo $this->formRow($form->get('categoryid')->setAttribute('class', 'form-control'));
    ?>
</div>
<div class="form-group">
    <?php
    echo $this->formRow($form->get('title')->setAttribute('class', 'form-control'));
    ?>
</div>
<div class="form-group">
    <?php
    echo $this->formRow($form->get('urlrewrite')->setAttribute('class', 'form-control'));
    ?>
</div>
<div class="form-group">
    <?php
    echo $this->formRow($form->get('quantity')->setAttribute('class', 'form-control'));
    ?>
</div>
<div class="form-group">
    <?php
    echo $this->formRow($form->get('price')->setAttribute('class', 'form-control'));
    ?>
</div>
<div class="form-group">
    <?php
    if(null!= $form->get('img')) {
        echo '<img src="\assets\\'. $form->get('img')->getValue() .'" alt="" /><br/>';
    }
    echo $this->formRow($form->get('img')->setAttribute('class', 'form-control'));
    ?>
</div>
<div class="form-group">
    <?php
    echo $this->formRow($form->get('status')->setAttribute('class', 'form-control'));
    ?>
</div>
<div class="form-group">
    <?php
    echo $this->formRow($form->get('description')->setAttribute('class', 'form-control'));
    ?>
</div>
<div class="btn-group">
    <?php
    echo $this->formSubmit($form->get('submit')->setAttribute('class', 'btn btn-primary'));
    ?>
</div>
<?php
echo $this->form()->closeTag();
