<?php

$title = 'My products';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('product', array('action'=>'add'));?>">Add new product</a>
</p>

<table class="table">
<tr>
    <th>Title</th>
    <th>Quantity</th>
    <th>Price</th>
    <th>Picture</th>
    <th>Category</th>
    <th>Status</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($products as $product) : ?>
<tr>
    <td><?php echo $this->escapeHtml($product->title);?></td>
    <td><?php echo $this->escapeHtml($product->quantity);?></td>
    <td><?php echo $this->escapeHtml($product->price);?></td>
    <td><?php echo $this->escapeHtml($product->img);?></td>
    <td><?php echo $this->escapeHtml($product->categoryid);?></td>
    <td><?php echo $this->escapeHtml($product->status);?></td>
    <td>
        <a href="<?php echo $this->url('product',
            array('action'=>'edit', 'id' => $product->productid));?>">Edit</a>
        <a href="<?php echo $this->url('product',
            array('action'=>'delete', 'id' => $product->productid));?>">Delete</a>
    </td>
</tr>
<?php endforeach; ?>
</table>