<?php
$title = 'My products';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('product', array('action' => 'add')); ?>">Add new product</a>
</p>

<table class="table">
    <tr>
        <th>No.</th>
        <th>Title</th>
        <th>Quantity</th>
        <th>Price</th>
        <th>Picture</th>
        <th>Category</th>
        <th>Status</th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach ($products as $key => $product) : ?>
        <tr>
            <td><?php echo $key + 1 ?></td>
            <td><?php echo $this->escapeHtml($product->getTitle()); ?></td>
            <td><?php echo $this->escapeHtml($product->getQuantity()); ?></td>
            <td><?php echo $this->escapeHtml($product->getPrice()); ?></td>
            <td><?php echo $this->escapeHtml($product->getImg()); ?></td>
            <td><?php echo $this->escapeHtml($product->getCategoryId()); ?></td>
            <td><?php echo $this->escapeHtml($product->getStatus()); ?></td>
            <td>
                <a href="<?php echo $this->url('product', array('action' => 'edit', 'id' => $product->getProductId()));
        ?>">Edit</a>
                <a href="<?php echo $this->url('product', array('action' => 'delete', 'id' => $product->getProductId()));
        ?>">Delete</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>